# https://github.com/pages-themes/minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
title: Phlexicon
description: "A catalog of phonemes in hundreds of languages, dialects, and lexicons—both signed and spoken."